config/routes.rb
BestBeerHere::Application.routes.draw do
  devise_for :users
  
  root :to => "home#index"
  
  get 'pages/beerpedia', :controller => 'pages'
  
  resources :beers, :controller => 'beers', :only => [:index, :show]
  get "/breweries/json" => "breweries#json", :format => :json
  resources :bars, :controller => 'bars', :only => [:index, :show]
  resources :breweries, :controller => 'breweries', :only => [:index, :show]
  resources :styles, :controller => 'styles', :only => [:index, :show]
  resources :ingredients, :controller => 'ingredients', :only => [:index, :show]
  
  scope "admin", :as => 'admin' do
    root :to => 'admin#index'
    
    resources :beers,  :controller => 'admin/beers'
    resources :breweries,  :controller => 'admin/breweries'
    resources :styles,  :controller => 'admin/styles'
    resources :ingredients,  :controller => 'admin/ingredients'
    resources :bars,  :controller => 'admin/bars'
  end
  

end

app/models/style.rb
class Style
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  field :name, :type => String
  slug :name
  field :description
  field :origin
  field :resource_url
  
  has_and_belongs_to_many :ingredients
  has_many :beers
  
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < AdminController
  def index
    @styles = Style.all
  end
  
  def new
    @style = Style.new
  end
    
  def create
    @style = Style.new(params[:style])
    if @style.save      
      flash[:notice] = 'Style was successfully created!'  
      return redirect_to admin_styles_path
    end
    render :action => 'new'
  end
  
  def edit
    @style = Style.find_by_slug(params[:id])
  end
  
  def update
    @style = Style.find_by_slug(params[:id])
    if @style.update_attributes(params[:style])      
      flash[:notice] = 'Style was successfully updated!'  
      return redirect_to admin_styles_path
    end
    render :action => 'new'
  end
  
  def show
    @style = Style.find_by_slug(params[:id])
  end

  def destroy
    @style = Style.find_by_slug(params[:id])
    flash[:notice] = 'Style was successfully destroyed.' if @style.destroy
    redirect_to(admin_styles_path)
  end
   
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def index
    @styles = Style.all
  end
  
  def show
    @style = Style.find_by_slug(params[:id])
  end
   
end

app/views/admin/styles/_form.html.haml
= semantic_form_for @style, :url => @style.new_record? ? admin_styles_path : admin_style_path(@style) do |f|
  = f.inputs do
    = f.input :name
    = f.input :description
    = f.input :origin
    = f.input :resource_url
    = f.input :ingredients, :as => :check_boxes, :collection => Ingredient.all
  = f.buttons do
    = f.button :submit

app/views/admin/styles/edit.html.haml
= render :partial => 'form'

app/views/admin/styles/index.html.haml
= link_to 'Add style here', new_admin_style_path

%table
  - @styles.each do |style|
    %tr{ :class => cycle(:odd, :even) }
      %td.text= style.name
      %td.action= link_to t('show'), admin_style_path(style)
      %td.action= link_to t('edit'), edit_admin_style_path(style)
      %td.action
        = button_to "Delete", { :action => "destroy", :id => style.id }, :confirm => "Are you sure?", :controller => 'style', :method => :delete

app/views/admin/styles/new.html.haml
= render :partial => 'form'

app/views/admin/styles/show.html.haml
= link_to 'EDIT THIS STYLE', edit_admin_style_path(@style)

= render :partial => 'layouts/style_show_page'