config/routes.rb
BestBeerHere::Application.routes.draw do
  devise_for :users
  
  root :to => "home#index"
  
  get 'pages/beerpedia', :controller => 'pages'
  
  resources :beers, :controller => 'beers', :only => [:index, :show]
  get "/breweries/json" => "breweries#json", :format => :json
  resources :bars, :controller => 'bars', :only => [:index, :show]
  resources :breweries, :controller => 'breweries', :only => [:index, :show]
  resources :styles, :controller => 'styles', :only => [:index, :show]
  resources :ingredients, :controller => 'ingredients', :only => [:index, :show]
  
  scope "admin", :as => 'admin' do
    root :to => 'admin#index'
    
    resources :beers,  :controller => 'admin/beers'
    resources :breweries,  :controller => 'admin/breweries'
    resources :styles,  :controller => 'admin/styles'
    resources :ingredients,  :controller => 'admin/ingredients'
    resources :bars,  :controller => 'admin/bars'
  end
  

end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  field :name, :type => String
  slug :name
  field :ing_type, :type => String
  field :description, :type => String
  field :resource_url, :type => String
  
  has_and_belongs_to_many :beers
  has_and_belongs_to_many :styles
  
end

app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < AdminController
  def index
    @ingredients = Ingredient.all
  end
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(params[:ingredient])
    if @ingredient.save      
      flash[:notice] = 'Ingredient was successfully created!'  
      return redirect_to admin_ingredients_path
    end
    render :action => 'new'
  end
  
  def show
    @ingredient = Ingredient.find_by_slug(params[:id])
  end
  
  def edit
    @ingredient = Ingredient.find_by_slug(params[:id])
  end
  
  def update
    @ingredient = Ingredient.find_by_slug(params[:id])
    if @ingredient.update_attributes(params[:ingredient])      
      flash[:notice] = 'Ingredient was successfully updated!'  
      return redirect_to admin_ingredients_path
    end
    render :action => 'new'
  end
  
  def destroy
    @ingredient = Ingredient.find_by_slug(params[:id])
    flash[:notice] = 'Ingredient was successfully destroyed.' if @ingredient.destroy
    redirect_to(admin_ingredients_path)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  
  def show
    @ingredient = Ingredient.find_by_slug(params[:id])
  end
   
end

app/views/admin/ingredients/_form.html.haml
= semantic_form_for @ingredient, :url => @ingredient.new_record? ? admin_ingredients_path : admin_ingredient_path(@ingredient) do |f|
  = f.inputs do
    = f.input :name
    = f.input :ing_type
    = f.input :description
    = f.input :resource_url
  = f.buttons do
    = f.button :submit

app/views/admin/ingredients/edit.html.haml
= render :partial => 'form'

app/views/admin/ingredients/index.html.haml
= link_to 'Add ingredient here', new_admin_ingredient_path

%table
  - @ingredients.each do |ingredient|
    %tr{ :class => cycle(:odd, :even) }
      %td.text= ingredient.name
      %td.action= link_to t('show'), admin_ingredient_path(ingredient)
      %td.action= link_to t('edit'), edit_admin_ingredient_path(ingredient)
      %td.action
        = button_to "Delete", { :action => "destroy", :id => ingredient.id }, :confirm => "Are you sure?", :controller => 'ingredient', :method => :delete

app/views/admin/ingredients/new.html.haml
= render :partial => 'form'

app/views/admin/ingredients/show.html.haml
= link_to 'EDIT THIS INGREDIENT', edit_admin_ingredient_path(@ingredient)

= render :partial => 'layouts/ingredient_show_page'