config/routes.rb
BestBeerHere::Application.routes.draw do
  devise_for :users
  
  root :to => "home#index"
  
  get 'pages/beerpedia', :controller => 'pages'
  
  resources :beers, :controller => 'beers', :only => [:index, :show]
  get "/breweries/json" => "breweries#json", :format => :json
  resources :bars, :controller => 'bars', :only => [:index, :show]
  resources :breweries, :controller => 'breweries', :only => [:index, :show]
  resources :styles, :controller => 'styles', :only => [:index, :show]
  resources :ingredients, :controller => 'ingredients', :only => [:index, :show]
  
  scope "admin", :as => 'admin' do
    root :to => 'admin#index'
    
    resources :beers,  :controller => 'admin/beers'
    resources :breweries,  :controller => 'admin/breweries'
    resources :styles,  :controller => 'admin/styles'
    resources :ingredients,  :controller => 'admin/ingredients'
    resources :bars,  :controller => 'admin/bars'
  end
  

end

app/models/bar.rb
class Bar
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  field :name
  slug :name
  field :address
  field :url
  field :yelp_url
  field :image_url
  
  has_and_belongs_to_many :beers
  
end

app/controllers/admin/bars_controller.rb
class Admin::BarsController < AdminController
  def index
    @bars = Bar.all
  end
  
  def new
    @bar = Bar.new
  end
  
  def create
    @bar = Bar.new(params[:bar])
    if @bar.save      
      flash[:notice] = 'Bar was successfully created!'  
      return redirect_to admin_bars_path
    end
    render :action => 'new'
  end
  
  def show
    @bar = Bar.find_by_slug(params[:id])
    @beers = @bar.beers
  end
  
  def edit
    @bar = Bar.find_by_slug(params[:id])
  end
  
  def update
    @bar = Bar.find_by_slug(params[:id])
    if @bar.update_attributes(params[:bar])       
      flash[:notice] = 'Bar was successfully updated!'  
      return redirect_to admin_bars_path
    end
    render :action => 'new'
  end
  
  def destroy
    @bar = Bar.find_by_slug(params[:id])
    flash[:notice] = 'Bar was successfully destroyed.' if @bar.destroy
    redirect_to(admin_bars_path)
  end
   
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all
  end
  
  def show
    @bar = Bar.find_by_slug(params[:id])
    @beers = @bar.beers
  end
   
end

app/views/admin/bars/_form.html.haml
= semantic_form_for @bar, :url => @bar.new_record? ? admin_bars_path : admin_bar_path(@bar) do |f|
  = f.inputs do
    = f.input :name
    = f.input :address
    = f.input :url
    = f.input :image_url
    = f.input :yelp_url
    = f.input :beers, :as => :check_boxes, :collection => Beer.all
  = f.buttons do
    = f.button :submit

app/views/admin/bars/edit.html.haml
= render :partial => 'form'

app/views/admin/bars/index.html.haml
= link_to 'Add bar here', new_admin_bar_path

%table
  - @bars.each do |bar|
    %tr{ :class => cycle(:odd, :even) }
      %td.text= bar.name
      %td.action= link_to t('show'), admin_bar_path(bar)
      %td.action= link_to t('edit'), edit_admin_bar_path(bar)
      %td.action
        = button_to "Delete", { :action => "destroy", :id => bar.id }, :confirm => "Are you sure?", :controller => 'bar', :method => :delete

app/views/admin/bars/new.html.haml
= render :partial => 'form'

app/views/admin/bars/show.html.haml
= link_to 'EDIT THIS BAR', edit_admin_bar_path(@bar)

= render :partial => 'layouts/bar_show_page'