config/routes.rb
BestBeerHere::Application.routes.draw do
  devise_for :users
  
  root :to => "home#index"
  
  get 'pages/beerpedia', :controller => 'pages'
  
  resources :beers, :controller => 'beers', :only => [:index, :show]
  get "/breweries/json" => "breweries#json", :format => :json
  resources :bars, :controller => 'bars', :only => [:index, :show]
  resources :breweries, :controller => 'breweries', :only => [:index, :show]
  resources :styles, :controller => 'styles', :only => [:index, :show]
  resources :ingredients, :controller => 'ingredients', :only => [:index, :show]
  
  scope "admin", :as => 'admin' do
    root :to => 'admin#index'
    
    resources :beers,  :controller => 'admin/beers'
    resources :breweries,  :controller => 'admin/breweries'
    resources :styles,  :controller => 'admin/styles'
    resources :ingredients,  :controller => 'admin/ingredients'
    resources :bars,  :controller => 'admin/bars'
  end
  

end

app/models/beer.rb
class Beer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  field :name, :type => String
  slug :name
  field :abv, :type => Float
  field :description, :type => String
  field :image_url
  field :ba_url, :type => String
  field :rb_url, :type => String
  field :beer_url, :type => String
  
  belongs_to :brewery, index: true
  has_and_belongs_to_many :bars
  belongs_to :style
  has_and_belongs_to_many :ingredients
  
end

app/controllers/admin/beers_controller.rb
class Admin::BeersController < AdminController
  def index
    @beers = Beer.all
  end
  
  def new
    @beer = Beer.new
  end
  
  def create
    @beer = Beer.new(params[:beer])
    if @beer.save      
      flash[:notice] = 'Beer was successfully created!'  
      return redirect_to admin_beers_path
    end
    render :action => 'new'
  end
  
  def show
    @beer = Beer.find_by_slug(params[:id])
    @bars = @beer.bars
    @style = @beer.style
    @brewery = @beer.brewery
  end
  
  def edit
    @beer = Beer.find_by_slug(params[:id])
  end  
  
  def update
    @beer = Beer.find_by_slug(params[:id])
    if @beer.update_attributes(params[:beer])      
      flash[:notice] = 'Beer was successfully updated!'  
      return redirect_to admin_beers_path
    end
    render :action => 'new'
  end
  
  def destroy
    @beer = Beer.find_by_slug(params[:id])
    flash[:notice] = 'Beer was successfully destroyed.' if @beer.destroy
    redirect_to(admin_beers_path)
  end
   
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all
  end
  
  def show
    @beer = Beer.find_by_slug(params[:id])
    @style = @beer.style
    @bars = @beer.bars
    @brewery = @beer.brewery
  end
   
end

app/views/admin/beers/_form.html.haml
= semantic_form_for @beer, :url => @beer.new_record? ? admin_beers_path : admin_beer_path(@beer) do |f|
  = f.inputs do
    = f.input :name
    = f.input :brewery, :collection => Brewery.all
    = f.input :style, :collection => Style.all
    = f.input :ingredients, :as => :check_boxes, :collection => Ingredient.all
    = f.input :abv
    = f.input :description
    = f.input :ba_url
    = f.input :rb_url
    = f.input :beer_url
    = f.input :image_url
  = f.buttons do
    = f.button :submit
  

app/views/admin/beers/edit.html.haml
= render :partial => 'form'

app/views/admin/beers/index.html.haml
= link_to 'Add beer here', new_admin_beer_path

%table
  - @beers.each do |beer|
    %tr{ :class => cycle(:odd, :even) }
      %td.text= beer.name
      %td.action= link_to t('show'), admin_beer_path(beer)
      %td.action= link_to t('edit'), edit_admin_beer_path(beer)
      %td.action
        = button_to "Delete", { :action => "destroy", :id => beer.id }, :confirm => "Are you sure?", :controller => 'beer', :method => :delete

app/views/admin/beers/new.html.haml
= render :partial => 'form'

app/views/admin/beers/show.html.haml
= link_to 'EDIT THIS BEER', edit_admin_beer_path(@beer) 
= render :partial => 'layouts/beer_show_page'